<?php

namespace service\controllers;
use common\components\CommonFun;
use common\models\Members;
use common\models\WeixinFans;
use yii\db\Exception;
use yii\web\Controller;


class OauthController extends Controller {
    public $weixin;
    public $auth_access_token = 'auth_access_token';
    public $redirectUrl = 'https://service.shenglife.cn/oauth/weixin.html';
    public $data = [];

    public function init() {
        $this->weixin = \Yii::$app->wechat;
        parent::init(); // TODO: Change the autogenerated stub
    }

    function actionWebAuth($openid = '', $state = ''){
        $cache = CommonFun::getCache($this->auth_access_token.$openid);
        if ($cache == null || (isset($cache['expires']) && $cache['expires'] < YII_BEGIN_TIME)) {
            //如果TOKEN过期，使用refresh_token刷新新token
            $res = ($cache)?$this->weixin->refreshOauth2AccessToken($cache['refresh_token']):['errcode'=>'10000'];
            if(isset($res['errcode'])){
                $target = $this->weixin->getOauth2AuthorizeUrl($this->redirectUrl, $state, 'snsapi_userinfo');
                \Yii::$app->controller->redirect($target);
                \Yii::$app->end();
            }else{
                $res['expires'] = time() + (int)$res['expires_in'];
                CommonFun::setCache($this->auth_access_token.$res['openid'], $res, $res['expires_in']);
                $this->data['openid'] = $res['openid'];
            }
        }
        $query = ['openid'=>$cache['openid']];
//        $refer = 'http://weixin.shenglife.cn/?'.http_build_query($query);
        $refer = 'https://weixin.shenglife.cn/'.base64_decode($state).'?'.http_build_query($query);
        \Yii::$app->controller->redirect($refer);
        \Yii::$app->end();
    }

    //回调
    function actionWeixin($code, $state=''){
        $res = $this->weixin->getOauth2AccessToken($code);
        CommonFun::log($res, 'wxfans', 'auth');
        if($res == null || isset($res['errcode'])){
            $this->data['error'] = $res['errmsg'];
        }else{
            //查看授权数据
            $wx = WeixinFans::getInfo($res['openid']);
            if(!$wx){
                $fans = $this->weixin->getSnsMemberInfo($res['openid'], $res['access_token']);
                CommonFun::log($fans, 'no-wxfans', 'auth');
                if(!isset($fans['errcode'])){
                    $fans['subscribe_time'] = time();
                    $member = WeixinFans::register($fans);
                    if(!$member){
                        exit;
                    }
                }
            }else{
                if ($wx->unionid == '' && isset($res['unionid']) && $res['unionid'] != ''){
                    $wx->unionid = $res['unionid'];
                    $wx->save();
                }
            }

            $res['expires'] = time() + (int)$res['expires_in'];
            CommonFun::setCache($this->auth_access_token.$res['openid'], $res, $res['expires_in']);
            $this->data['openid'] = $res['openid'];
        }

        $query = ['openid'=>$res['openid']];
//        $refer = 'http://weixin.shenglife.cn/?'.http_build_query($query);
        $refer = 'http://weixin.shenglife.cn/'.base64_decode($state).'?'.http_build_query($query);
        \Yii::$app->controller->redirect($refer);
        \Yii::$app->end();
    }

    //小程序的授权
    function actionMiniprogram($code){
        $appid = 'wxc79ca52b26d4b6d9';
        $appSecret = 'bf707d67011c91e193bf8977ce0f1831';
        $url = 'https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code';
        $url = str_replace('APPID', $appid, $url);
        $url = str_replace('SECRET', $appSecret, $url);
        $url = str_replace('JSCODE', $code, $url);

        $res = CommonFun::curlGet($url);
        return $res;
        exit;
    }


//    function actionShare($state = ''){
//        $refer = 'http://weixin.shenglife.cn/#/'.base64_decode($state);
//        \Yii::$app->controller->redirect($refer);
//        \Yii::$app->end();
//    }
}
